"""Generate web/lib/index-membership.ts from the seed constituent CSVs.

The Run Analysis "index" quick baskets (S&P 500 / ASX 200 / S&P/TSX 60) must
resolve to the *actual* index constituents we cover — not "every stock in that
market" (which would silently absorb Request-a-Ticker additions). The membership
lists are static reference data sourced from the point-in-time constituent CSVs
in this folder, so we bake them into a committed TypeScript module rather than a
DB table.

Refresh cadence (weekly/monthly, owner's call): update the relevant CSV with the
current constituents, then re-run this generator and commit the regenerated
web/lib/index-membership.ts:

    python analytics/universe/generate_index_membership.py

Ticker normalisation: US symbols use yfinance's class-share form (a dash, e.g.
`BRK-B`), while constituent lists often use a dot (`BRK.B`). For the US list we
map `.` -> `-` so class shares match the stored ticker. AU/CA tickers already
carry their `.AX` / `.TO` suffix and are emitted verbatim. A constituent we do
not cover simply won't intersect the universe at runtime, so it's harmless to
include — the basket is always `members ∩ universe`.
"""

from __future__ import annotations

import csv
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_OUT = _HERE.parent.parent / "web" / "lib" / "index-membership.ts"

# (index id, source CSV, US-style dot->dash normalisation?)
_SOURCES = [
    ("sp500", "sp500.csv", True),
    ("asx200", "asx200.csv", False),
    ("tsx60", "tsx60.csv", False),
]


def _load(csv_name: str, us_normalise: bool) -> list[str]:
    path = _HERE / csv_name
    seen: set[str] = set()
    out: list[str] = []
    with path.open(newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            t = (row.get("ticker") or "").strip().upper()
            if not t:
                continue
            if us_normalise:
                t = t.replace(".", "-")  # BRK.B -> BRK-B (yfinance class-share form)
            if t not in seen:
                seen.add(t)
                out.append(t)
    return sorted(out)


def main() -> None:
    blocks: list[str] = []
    summary: list[str] = []
    for index_id, csv_name, us_norm in _SOURCES:
        tickers = _load(csv_name, us_norm)
        summary.append(f"//   {index_id}: {len(tickers)} constituents (from {csv_name})")
        lines = ",\n".join(f"    '{t}'" for t in tickers)
        blocks.append(f"  {index_id}: new Set<string>([\n{lines},\n  ]),")

    body = (
        "// AUTO-GENERATED by analytics/universe/generate_index_membership.py — DO NOT EDIT.\n"
        "//\n"
        "// Real index constituents (point-in-time) used by the Run Analysis index\n"
        "// baskets, so they resolve to the actual S&P 500 / ASX 200 / S&P/TSX 60 names\n"
        "// we cover rather than every stock in the market. Refresh by updating the\n"
        "// source CSV(s) and re-running the generator, then commit this file.\n"
        "//\n"
        "// Source CSVs (analytics/universe/):\n"
        + "\n".join(summary)
        + "\n\n"
        "export type IndexId = 'sp500' | 'asx200' | 'tsx60';\n\n"
        "export const INDEX_MEMBERS: Record<IndexId, ReadonlySet<string>> = {\n"
        + "\n".join(blocks)
        + "\n};\n"
    )

    # newline="\n" so regenerating on any platform yields LF (deterministic — no
    # spurious CRLF diffs when the owner refreshes the lists).
    _OUT.write_text(body, encoding="utf-8", newline="\n")
    print(f"Wrote {_OUT} ({_OUT.stat().st_size} bytes)")
    for line in summary:
        print(line.replace("//   ", "  "))


if __name__ == "__main__":
    main()
